# -------------------------------------
# AMT (Asset Management Table) utilities
# -------------------------------------
"""
Module for processing AMT YAML files.

AMT files are YAML files with a specific structure containing asset definitions
under the 'amt' key, where each asset has an 'Underlying' identifier.

This package provides utilities for:
- Loading and querying AMT files (loader)
- Extracting tickers from assets (tickers)
- Expanding schedules and building straddles (schedules)

Imports are lazy to avoid RuntimeWarning when running submodules as scripts.
Use: from specparser.amt import load_amt, expand, etc.
"""

__all__ = [
    # loader
    "load_amt",
    "clear_cache",
    "get_value",
    "get_aum",
    "get_leverage",
    "get_asset",
    "find_assets",
    "cached_assets",
    "get_table",
    "_iter_assets",
    "assets",
    "asset_class",
    "_compile_rules",
    "_match_rules",
    "asset_table",
    "asset_group",
    # table utilities (from table.py)
    "table_to_columns",
    "table_to_rows",
    "table_to_arrow",
    "table_to_jsonable",
    "table_orientation",
    "table_nrows",
    "table_validate",
    "table_column",
    "table_select_columns",
    "table_add_column",
    "table_drop_columns",
    "table_replace_value",
    "table_bind_rows",
    "table_unique_rows",
    "table_head",
    "table_sample",
    "table_stack_cols",
    "table_left_join",
    "table_inner_join",
    "table_unchop",
    "table_chop",
    "table_explode_arrow",
    "table_pivot_wider",
    "table_lag",
    "table_lead",
    "format_table",
    "print_table",
    "show_table",
    # u8m (uint8 matrix) table functions
    "u8m_from_matrix",
    "u8m_column",
    "table_u8m2arrow",
    # arrow compute functions
    # arithmetic
    "table_add_arrow",
    "table_subtract_arrow",
    "table_multiply_arrow",
    "table_divide_arrow",
    "table_negate_arrow",
    "table_abs_arrow",
    "table_sign_arrow",
    "table_power_arrow",
    "table_sqrt_arrow",
    "table_exp_arrow",
    "table_ln_arrow",
    "table_log10_arrow",
    "table_log2_arrow",
    "table_round_arrow",
    "table_ceil_arrow",
    "table_floor_arrow",
    "table_trunc_arrow",
    # trigonometric
    "table_sin_arrow",
    "table_cos_arrow",
    "table_tan_arrow",
    "table_asin_arrow",
    "table_acos_arrow",
    "table_atan_arrow",
    "table_atan2_arrow",
    # comparison
    "table_equal_arrow",
    "table_not_equal_arrow",
    "table_less_arrow",
    "table_less_equal_arrow",
    "table_greater_arrow",
    "table_greater_equal_arrow",
    # null/value checks
    "table_is_null_arrow",
    "table_is_valid_arrow",
    "table_is_nan_arrow",
    "table_is_finite_arrow",
    "table_is_in_arrow",
    # logical
    "table_and_arrow",
    "table_or_arrow",
    "table_xor_arrow",
    "table_invert_arrow",
    # string
    "table_upper_arrow",
    "table_lower_arrow",
    "table_capitalize_arrow",
    "table_title_arrow",
    "table_strip_arrow",
    "table_lstrip_arrow",
    "table_rstrip_arrow",
    "table_length_arrow",
    "table_starts_with_arrow",
    "table_ends_with_arrow",
    "table_contains_arrow",
    "table_replace_substr_arrow",
    "table_split_arrow",
    # aggregates
    "table_summarize_arrow",
    "table_sum_arrow",
    "table_mean_arrow",
    "table_min_arrow",
    "table_max_arrow",
    "table_count_arrow",
    "table_count_distinct_arrow",
    "table_stddev_arrow",
    "table_variance_arrow",
    "table_first_arrow",
    "table_last_arrow",
    "table_any_arrow",
    "table_all_arrow",
    # cumulative
    "table_cumsum_arrow",
    "table_cumprod_arrow",
    "table_cummin_arrow",
    "table_cummax_arrow",
    "table_cummean_arrow",
    "table_diff_arrow",
    # selection
    "table_if_else_arrow",
    "table_coalesce_arrow",
    "table_fill_null_arrow",
    "table_fill_null_forward_arrow",
    "table_fill_null_backward_arrow",
    # filter
    "table_filter_arrow",
    # backward compatibility alias
    "bind_rows",
    # tickers
    "filter_tickers",
    "clear_ticker_caches",
    # asset_straddle_tickers
    "get_asset_straddle_tickers",
    "find_assets_straddles_tickers",
    "split_ticker",
    "make_fut_ticker",
    "asset_straddle_ticker_key",
    # chain
    "fut_norm2act",
    "fut_act2norm",
    "clear_chain_caches",
    # prices
    "get_prices",
    "actions",
    "get_straddle_actions",
    "get_straddle_valuation",
    "get_straddle_backtests",
    "get_straddle_backtests_numba",
    "build_price_arrays",
    "build_price_matrix",
    "load_all_prices",
    "load_prices_arrow",
    "clear_prices_arrow",
    "load_prices_matrix",
    "get_prices_matrix",
    "set_prices_matrix",
    "clear_prices_matrix",
    "PriceMatrix",
    "load_prices_numba",
    "get_prices_numba",
    "set_prices_numba",
    "clear_prices_numba",
    "PricesNumba",
    "set_prices_dict",
    "get_price",
    "clear_prices_dict",
    "clear_prices_connection_cache",
    "clear_override_cache",
    "prices_last",
    "prices_query",
    # valuation models
    "model_ES",
    "model_NS",
    "model_BS",
    "MODEL_DISPATCH",
    # schedules
    "get_schedule",
    "get_schedule_count",
    "find_schedules",
    "clear_schedule_caches",
    "_split_code_value",
    "find_straddle_yrs",
    "find_straddle_ym",
    "get_straddle_yrs",
    "get_expand_ym",
    "get_days_ym",
    "clear_days_cache",
    "count_straddle_days",
    "straddle_days",
    "count_straddles_days",
    "find_straddle_days",
    "find_straddle_days_arrow",
    "find_straddle_days_numba",
    "clear_calendar_cache",
    # u8m schedule functions
    "get_schedule_u8m",
    "find_schedules_u8m",
    "find_straddle_yrs_u8m",
    "straddles_u8m_to_strings",
    "find_straddle_days_u8m",
    "straddle_days_u8m_to_arrow",
    # straddle parsing
    "ntr",
    "ntry",
    "ntrm",
    "xpr",
    "xpry",
    "xprm",
    "ntrc",
    "ntrv",
    "xprc",
    "xprv",
    "wgt",
    # strings (fast byte matrix operations)
    "strs2u8mat",
    "u8m2S",
    "u8m2s",
    "u82S",
    "u82s",
    "s2u8",
    "sep",
    "make_u8mat",
    "ASCII_MAP",
    "ASCII_0",
    "ASCII_1",
    "ASCII_DASH",
    "ASCII_SPACE",
    "ASCII_N",
    "ASCII_F",
    "ASCII_A",
    "ASCII_PIPE",
    # strings - date parsing
    "read_1digit",
    "read_2digits",
    "read_4digits",
    "get_uint8_ym",
    "get_uint8_ymd",
    # strings - date writing
    "make_ym",
    "add_months_ym",
    "add_months_ym_inplace",
    "add_months2specs_inplace",
    "add_months2specs_inplace_NF",
    # strings - calendar functions
    "is_leap_year",
    "days_per_month",
    "last_day_of_month",
    "days_between",
    "add_months",
    "make_ym_matrix",
    "make_ymd_matrix",
    "make_calendar_from_ranges",
    "make_calendar_from_ranges_par",
    "make_calendar_from_specs_par",
    # strings - cartesian product
    "cartesian_product",
    "cartesian_product_np",
    "cartesian_product_par",
    # strings - unfurl
    "unfurl",
    "unfurl_by_spec",
    "unfurl_by_spec_sep",
    "unfurl_concat",
    "unfurl_concat_sep",
    # strings - field extraction
    "nth_occurrence_char",
    "nth_occurrence",
    "field",
]

# Lazy import mapping: attribute -> (module, name)
_LAZY_IMPORTS = {
    # loader
    "load_amt": (".loader", "load_amt"),
    "clear_cache": (".loader", "clear_cache"),
    "get_value": (".loader", "get_value"),
    "get_aum": (".loader", "get_aum"),
    "get_leverage": (".loader", "get_leverage"),
    "get_asset": (".loader", "get_asset"),
    "find_assets": (".loader", "find_assets"),
    "cached_assets": (".loader", "cached_assets"),
    "get_table": (".loader", "get_table"),
    "_iter_assets": (".loader", "_iter_assets"),
    "assets": (".loader", "assets"),
    "asset_class": (".loader", "asset_class"),
    "_compile_rules": (".loader", "_compile_rules"),
    "_match_rules": (".loader", "_match_rules"),
    "asset_table": (".loader", "asset_table"),
    "asset_group": (".loader", "asset_group"),
    # table utilities (from table.py)
    "table_to_columns": (".table", "table_to_columns"),
    "table_to_rows": (".table", "table_to_rows"),
    "table_to_arrow": (".table", "table_to_arrow"),
    "table_to_jsonable": (".table", "table_to_jsonable"),
    "table_orientation": (".table", "table_orientation"),
    "table_nrows": (".table", "table_nrows"),
    "table_validate": (".table", "table_validate"),
    "table_column": (".table", "table_column"),
    "table_select_columns": (".table", "table_select_columns"),
    "table_add_column": (".table", "table_add_column"),
    "table_drop_columns": (".table", "table_drop_columns"),
    "table_replace_value": (".table", "table_replace_value"),
    "table_bind_rows": (".table", "table_bind_rows"),
    "table_unique_rows": (".table", "table_unique_rows"),
    "table_head": (".table", "table_head"),
    "table_sample": (".table", "table_sample"),
    "table_stack_cols": (".table", "table_stack_cols"),
    "table_left_join": (".table", "table_left_join"),
    "table_inner_join": (".table", "table_inner_join"),
    "table_unchop": (".table", "table_unchop"),
    "table_chop": (".table", "table_chop"),
    "table_explode_arrow": (".table", "table_explode_arrow"),
    "table_pivot_wider": (".table", "table_pivot_wider"),
    "table_lag": (".table", "table_lag"),
    "table_lead": (".table", "table_lead"),
    "format_table": (".table", "format_table"),
    "print_table": (".table", "print_table"),
    "show_table": (".table", "show_table"),
    # u8m (uint8 matrix) table functions
    "u8m_from_matrix": (".table", "u8m_from_matrix"),
    "u8m_column": (".table", "u8m_column"),
    "table_u8m2arrow": (".table", "table_u8m2arrow"),
    # arrow compute functions
    # arithmetic
    "table_add_arrow": (".table", "table_add_arrow"),
    "table_subtract_arrow": (".table", "table_subtract_arrow"),
    "table_multiply_arrow": (".table", "table_multiply_arrow"),
    "table_divide_arrow": (".table", "table_divide_arrow"),
    "table_negate_arrow": (".table", "table_negate_arrow"),
    "table_abs_arrow": (".table", "table_abs_arrow"),
    "table_sign_arrow": (".table", "table_sign_arrow"),
    "table_power_arrow": (".table", "table_power_arrow"),
    "table_sqrt_arrow": (".table", "table_sqrt_arrow"),
    "table_exp_arrow": (".table", "table_exp_arrow"),
    "table_ln_arrow": (".table", "table_ln_arrow"),
    "table_log10_arrow": (".table", "table_log10_arrow"),
    "table_log2_arrow": (".table", "table_log2_arrow"),
    "table_round_arrow": (".table", "table_round_arrow"),
    "table_ceil_arrow": (".table", "table_ceil_arrow"),
    "table_floor_arrow": (".table", "table_floor_arrow"),
    "table_trunc_arrow": (".table", "table_trunc_arrow"),
    # trigonometric
    "table_sin_arrow": (".table", "table_sin_arrow"),
    "table_cos_arrow": (".table", "table_cos_arrow"),
    "table_tan_arrow": (".table", "table_tan_arrow"),
    "table_asin_arrow": (".table", "table_asin_arrow"),
    "table_acos_arrow": (".table", "table_acos_arrow"),
    "table_atan_arrow": (".table", "table_atan_arrow"),
    "table_atan2_arrow": (".table", "table_atan2_arrow"),
    # comparison
    "table_equal_arrow": (".table", "table_equal_arrow"),
    "table_not_equal_arrow": (".table", "table_not_equal_arrow"),
    "table_less_arrow": (".table", "table_less_arrow"),
    "table_less_equal_arrow": (".table", "table_less_equal_arrow"),
    "table_greater_arrow": (".table", "table_greater_arrow"),
    "table_greater_equal_arrow": (".table", "table_greater_equal_arrow"),
    # null/value checks
    "table_is_null_arrow": (".table", "table_is_null_arrow"),
    "table_is_valid_arrow": (".table", "table_is_valid_arrow"),
    "table_is_nan_arrow": (".table", "table_is_nan_arrow"),
    "table_is_finite_arrow": (".table", "table_is_finite_arrow"),
    "table_is_in_arrow": (".table", "table_is_in_arrow"),
    # logical
    "table_and_arrow": (".table", "table_and_arrow"),
    "table_or_arrow": (".table", "table_or_arrow"),
    "table_xor_arrow": (".table", "table_xor_arrow"),
    "table_invert_arrow": (".table", "table_invert_arrow"),
    # string
    "table_upper_arrow": (".table", "table_upper_arrow"),
    "table_lower_arrow": (".table", "table_lower_arrow"),
    "table_capitalize_arrow": (".table", "table_capitalize_arrow"),
    "table_title_arrow": (".table", "table_title_arrow"),
    "table_strip_arrow": (".table", "table_strip_arrow"),
    "table_lstrip_arrow": (".table", "table_lstrip_arrow"),
    "table_rstrip_arrow": (".table", "table_rstrip_arrow"),
    "table_length_arrow": (".table", "table_length_arrow"),
    "table_starts_with_arrow": (".table", "table_starts_with_arrow"),
    "table_ends_with_arrow": (".table", "table_ends_with_arrow"),
    "table_contains_arrow": (".table", "table_contains_arrow"),
    "table_replace_substr_arrow": (".table", "table_replace_substr_arrow"),
    "table_split_arrow": (".table", "table_split_arrow"),
    # aggregates
    "table_summarize_arrow": (".table", "table_summarize_arrow"),
    "table_sum_arrow": (".table", "table_sum_arrow"),
    "table_mean_arrow": (".table", "table_mean_arrow"),
    "table_min_arrow": (".table", "table_min_arrow"),
    "table_max_arrow": (".table", "table_max_arrow"),
    "table_count_arrow": (".table", "table_count_arrow"),
    "table_count_distinct_arrow": (".table", "table_count_distinct_arrow"),
    "table_stddev_arrow": (".table", "table_stddev_arrow"),
    "table_variance_arrow": (".table", "table_variance_arrow"),
    "table_first_arrow": (".table", "table_first_arrow"),
    "table_last_arrow": (".table", "table_last_arrow"),
    "table_any_arrow": (".table", "table_any_arrow"),
    "table_all_arrow": (".table", "table_all_arrow"),
    # cumulative
    "table_cumsum_arrow": (".table", "table_cumsum_arrow"),
    "table_cumprod_arrow": (".table", "table_cumprod_arrow"),
    "table_cummin_arrow": (".table", "table_cummin_arrow"),
    "table_cummax_arrow": (".table", "table_cummax_arrow"),
    "table_cummean_arrow": (".table", "table_cummean_arrow"),
    "table_diff_arrow": (".table", "table_diff_arrow"),
    # selection
    "table_if_else_arrow": (".table", "table_if_else_arrow"),
    "table_coalesce_arrow": (".table", "table_coalesce_arrow"),
    "table_fill_null_arrow": (".table", "table_fill_null_arrow"),
    "table_fill_null_forward_arrow": (".table", "table_fill_null_forward_arrow"),
    "table_fill_null_backward_arrow": (".table", "table_fill_null_backward_arrow"),
    # filter
    "table_filter_arrow": (".table", "table_filter_arrow"),
    # backward compatibility alias
    "bind_rows": (".table", "table_bind_rows"),
    # tickers
    "filter_tickers": (".tickers", "filter_tickers"),
    "clear_ticker_caches": (".tickers", "clear_ticker_caches"),
    # asset_straddle_tickers
    "get_asset_straddle_tickers": (".asset_straddle_tickers", "get_asset_straddle_tickers"),
    "find_assets_straddles_tickers": (".asset_straddle_tickers", "find_assets_straddles_tickers"),
    "split_ticker": (".asset_straddle_tickers", "split_ticker"),
    "make_fut_ticker": (".asset_straddle_tickers", "make_fut_ticker"),
    "asset_straddle_ticker_key": (".asset_straddle_tickers", "asset_straddle_ticker_key"),
    # chain
    "fut_norm2act": (".chain", "fut_norm2act"),
    "fut_act2norm": (".chain", "fut_act2norm"),
    "clear_chain_caches": (".chain", "clear_chain_caches"),
    # prices (data access)
    "get_prices": (".prices", "get_prices"),
    "load_all_prices": (".prices", "load_all_prices"),
    "build_price_arrays": (".prices", "build_price_arrays"),
    "build_price_matrix": (".prices", "build_price_matrix"),
    "load_prices_matrix": (".prices", "load_prices_matrix"),
    "get_prices_matrix": (".prices", "get_prices_matrix"),
    "set_prices_matrix": (".prices", "set_prices_matrix"),
    "clear_prices_matrix": (".prices", "clear_prices_matrix"),
    "PriceMatrix": (".prices", "PriceMatrix"),
    "load_prices_numba": (".prices", "load_prices_numba"),
    "get_prices_numba": (".prices", "get_prices_numba"),
    "set_prices_numba": (".prices", "set_prices_numba"),
    "clear_prices_numba": (".prices", "clear_prices_numba"),
    "PricesNumba": (".prices", "PricesNumba"),
    "set_prices_dict": (".prices", "set_prices_dict"),
    "get_price": (".prices", "get_price"),
    "clear_prices_dict": (".prices", "clear_prices_dict"),
    "clear_prices_connection_cache": (".prices", "clear_prices_connection_cache"),
    "prices_last": (".prices", "prices_last"),
    "prices_query": (".prices", "prices_query"),
    # valuation (actions & models)
    "actions": (".valuation", "actions"),
    "get_straddle_actions": (".valuation", "get_straddle_actions"),
    "get_straddle_valuation": (".valuation", "get_straddle_valuation"),
    "get_straddle_backtests": (".valuation", "get_straddle_backtests"),
    "get_straddle_backtests_numba": (".valuation_numba", "get_straddle_backtests_numba"),
    "load_prices_arrow": (".valuation", "load_prices_arrow"),
    "clear_prices_arrow": (".valuation", "clear_prices_arrow"),
    "clear_override_cache": (".valuation", "clear_override_cache"),
    "model_ES": (".valuation", "model_ES"),
    "model_NS": (".valuation", "model_NS"),
    "model_BS": (".valuation", "model_BS"),
    "MODEL_DISPATCH": (".valuation", "MODEL_DISPATCH"),
    # schedules
    "get_schedule": (".schedules", "get_schedule"),
    "get_schedule_count": (".schedules", "get_schedule_count"),
    "find_schedules": (".schedules", "find_schedules"),
    "clear_schedule_caches": (".schedules", "clear_schedule_caches"),
    "_split_code_value": (".schedules", "_split_code_value"),
    "find_straddle_yrs": (".schedules", "find_straddle_yrs"),
    "find_straddle_ym": (".schedules", "find_straddle_ym"),
    "get_straddle_yrs": (".schedules", "get_straddle_yrs"),
    "get_expand_ym": (".schedules", "get_expand_ym"),
    "get_days_ym": (".schedules", "get_days_ym"),
    "clear_days_cache": (".schedules", "clear_days_cache"),
    "count_straddle_days": (".schedules", "count_straddle_days"),
    "straddle_days": (".schedules", "straddle_days"),
    "count_straddles_days": (".schedules", "count_straddles_days"),
    "find_straddle_days": (".schedules", "find_straddle_days"),
    "find_straddle_days_arrow": (".schedules", "find_straddle_days_arrow"),
    "find_straddle_days_numba": (".schedules", "find_straddle_days_numba"),
    "clear_calendar_cache": (".schedules", "clear_calendar_cache"),
    # u8m schedule functions
    "get_schedule_u8m": (".schedules", "get_schedule_u8m"),
    "find_schedules_u8m": (".schedules", "find_schedules_u8m"),
    "find_straddle_yrs_u8m": (".schedules", "find_straddle_yrs_u8m"),
    "straddles_u8m_to_strings": (".schedules", "straddles_u8m_to_strings"),
    "find_straddle_days_u8m": (".schedules", "find_straddle_days_u8m"),
    "straddle_days_u8m_to_arrow": (".schedules", "straddle_days_u8m_to_arrow"),
    # straddle parsing
    "ntr": (".schedules", "ntr"),
    "ntry": (".schedules", "ntry"),
    "ntrm": (".schedules", "ntrm"),
    "xpr": (".schedules", "xpr"),
    "xpry": (".schedules", "xpry"),
    "xprm": (".schedules", "xprm"),
    "ntrc": (".schedules", "ntrc"),
    "ntrv": (".schedules", "ntrv"),
    "xprc": (".schedules", "xprc"),
    "xprv": (".schedules", "xprv"),
    "wgt": (".schedules", "wgt"),
    # strings (fast byte matrix operations)
    "strs2u8mat": (".strings", "strs2u8mat"),
    "u8m2S": (".strings", "u8m2S"),
    "u8m2s": (".strings", "u8m2s"),
    "u82S": (".strings", "u82S"),
    "u82s": (".strings", "u82s"),
    "s2u8": (".strings", "s2u8"),
    "sep": (".strings", "sep"),
    "make_u8mat": (".strings", "make_u8mat"),
    "ASCII_MAP": (".strings", "ASCII_MAP"),
    "ASCII_0": (".strings", "ASCII_0"),
    "ASCII_1": (".strings", "ASCII_1"),
    "ASCII_DASH": (".strings", "ASCII_DASH"),
    "ASCII_SPACE": (".strings", "ASCII_SPACE"),
    "ASCII_N": (".strings", "ASCII_N"),
    "ASCII_F": (".strings", "ASCII_F"),
    "ASCII_A": (".strings", "ASCII_A"),
    "ASCII_PIPE": (".strings", "ASCII_PIPE"),
    # strings - date parsing
    "read_1digit": (".strings", "read_1digit"),
    "read_2digits": (".strings", "read_2digits"),
    "read_4digits": (".strings", "read_4digits"),
    "get_uint8_ym": (".strings", "get_uint8_ym"),
    "get_uint8_ymd": (".strings", "get_uint8_ymd"),
    # strings - date writing
    "make_ym": (".strings", "make_ym"),
    "add_months_ym": (".strings", "add_months_ym"),
    "add_months_ym_inplace": (".strings", "add_months_ym_inplace"),
    "add_months2specs_inplace": (".strings", "add_months2specs_inplace"),
    "add_months2specs_inplace_NF": (".strings", "add_months2specs_inplace_NF"),
    "sub_months_vec": (".strings", "sub_months_vec"),
    "ntrc_to_offset_span": (".strings", "ntrc_to_offset_span"),
    # strings - calendar functions
    "is_leap_year": (".strings", "is_leap_year"),
    "days_per_month": (".strings", "days_per_month"),
    "last_day_of_month": (".strings", "last_day_of_month"),
    "days_between": (".strings", "days_between"),
    "add_months": (".strings", "add_months"),
    "make_ym_matrix": (".strings", "make_ym_matrix"),
    "make_ymd_matrix": (".strings", "make_ymd_matrix"),
    "make_calendar_from_ranges": (".strings", "make_calendar_from_ranges"),
    "make_calendar_from_ranges_par": (".strings", "make_calendar_from_ranges_par"),
    "make_calendar_from_specs_par": (".strings", "make_calendar_from_specs_par"),
    # strings - cartesian product
    "cartesian_product": (".strings", "cartesian_product"),
    "cartesian_product_np": (".strings", "cartesian_product_np"),
    "cartesian_product_par": (".strings", "cartesian_product_par"),
    # strings - unfurl
    "unfurl": (".strings", "unfurl"),
    "unfurl_by_spec": (".strings", "unfurl_by_spec"),
    "unfurl_by_spec_sep": (".strings", "unfurl_by_spec_sep"),
    "unfurl_concat": (".strings", "unfurl_concat"),
    "unfurl_concat_sep": (".strings", "unfurl_concat_sep"),
    # strings - field extraction
    "nth_occurrence_char": (".strings", "nth_occurrence_char"),
    "nth_occurrence": (".strings", "nth_occurrence"),
    "field": (".strings", "field"),
}


def __getattr__(name: str):
    if name in _LAZY_IMPORTS:
        module_name, attr_name = _LAZY_IMPORTS[name]
        from importlib import import_module
        module = import_module(module_name, __package__)
        return getattr(module, attr_name)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
