# -------------------------------------
# AMT (Asset Management Table) utilities
# -------------------------------------
"""
Module for processing AMT YAML files.

AMT files are YAML files with a specific structure containing asset definitions
under the 'amt' key, where each asset has an 'Underlying' identifier.

This package provides utilities for:
- Loading and querying AMT files (loader)
- Extracting tickers from assets (tickers)
- Expanding schedules and building straddles (schedules)

Imports are lazy to avoid RuntimeWarning when running submodules as scripts.
Use: from specparser.amt import load_amt, expand, etc.
"""

__all__ = [
    # loader
    "load_amt",
    "clear_cache",
    "get_value",
    "get_aum",
    "get_leverage",
    "get_asset",
    "find_assets",
    "cached_assets",
    "get_table",
    "_iter_assets",
    "assets",
    "asset_class",
    "_compile_rules",
    "_match_rules",
    "asset_table",
    "asset_group",
    # table utilities (from table.py)
    "table_to_columns",
    "table_to_rows",
    "table_to_arrow",
    "table_to_jsonable",
    "table_orientation",
    "table_nrows",
    "table_validate",
    "table_column",
    "table_select_columns",
    "table_add_column",
    "table_drop_columns",
    "table_replace_value",
    "table_bind_rows",
    "table_unique_rows",
    "table_head",
    "table_sample",
    "table_stack_cols",
    "table_left_join",
    "table_inner_join",
    "table_unchop",
    "table_chop",
    "format_table",
    "print_table",
    # arrow compute functions
    # arithmetic
    "table_add_arrow",
    "table_subtract_arrow",
    "table_multiply_arrow",
    "table_divide_arrow",
    "table_negate_arrow",
    "table_abs_arrow",
    "table_sign_arrow",
    "table_power_arrow",
    "table_sqrt_arrow",
    "table_exp_arrow",
    "table_ln_arrow",
    "table_log10_arrow",
    "table_log2_arrow",
    "table_round_arrow",
    "table_ceil_arrow",
    "table_floor_arrow",
    "table_trunc_arrow",
    # trigonometric
    "table_sin_arrow",
    "table_cos_arrow",
    "table_tan_arrow",
    "table_asin_arrow",
    "table_acos_arrow",
    "table_atan_arrow",
    "table_atan2_arrow",
    # comparison
    "table_equal_arrow",
    "table_not_equal_arrow",
    "table_less_arrow",
    "table_less_equal_arrow",
    "table_greater_arrow",
    "table_greater_equal_arrow",
    # null/value checks
    "table_is_null_arrow",
    "table_is_valid_arrow",
    "table_is_nan_arrow",
    "table_is_finite_arrow",
    "table_is_in_arrow",
    # logical
    "table_and_arrow",
    "table_or_arrow",
    "table_xor_arrow",
    "table_invert_arrow",
    # string
    "table_upper_arrow",
    "table_lower_arrow",
    "table_capitalize_arrow",
    "table_title_arrow",
    "table_strip_arrow",
    "table_lstrip_arrow",
    "table_rstrip_arrow",
    "table_length_arrow",
    "table_starts_with_arrow",
    "table_ends_with_arrow",
    "table_contains_arrow",
    "table_replace_substr_arrow",
    "table_split_arrow",
    # aggregates
    "table_summarize_arrow",
    "table_sum_arrow",
    "table_mean_arrow",
    "table_min_arrow",
    "table_max_arrow",
    "table_count_arrow",
    "table_count_distinct_arrow",
    "table_stddev_arrow",
    "table_variance_arrow",
    "table_first_arrow",
    "table_last_arrow",
    "table_any_arrow",
    "table_all_arrow",
    # cumulative
    "table_cumsum_arrow",
    "table_cumprod_arrow",
    "table_cummin_arrow",
    "table_cummax_arrow",
    "table_cummean_arrow",
    "table_diff_arrow",
    # selection
    "table_if_else_arrow",
    "table_coalesce_arrow",
    "table_fill_null_arrow",
    "table_fill_null_forward_arrow",
    "table_fill_null_backward_arrow",
    # filter
    "table_filter_arrow",
    # backward compatibility alias
    "bind_rows",
    # tickers
    "_split_ticker",
    "get_tschemas",
    "find_tschemas",
    "fut_spec2ticker",
    "fut_norm2act",
    "fut_act2norm",
    "clear_normalized_cache",
    "_tschma_dict_expand_bbgfc",
    "_tschma_dict_expand_split",
    "asset_straddle_tickers",
    "get_straddle_days",
    "find_tickers",
    "find_tickers_ym",
    # schedules
    "get_schedule",
    "find_schedules",
    "_split_code_value",
    "find_straddle_yrs",
    "find_straddle_ym",
    "get_straddle_yrs",
    "get_expand_ym",
    "get_days_ym",
    "clear_days_cache",
    "count_straddle_days",
    "straddle_days",
    "count_straddles_days",
    "find_straddle_days",
    # straddle parsing
    "ntr",
    "ntry",
    "ntrm",
    "xpr",
    "xpry",
    "xprm",
    "ntrc",
    "ntrv",
    "xprc",
    "xprv",
    "wgt",
]

# Lazy import mapping: attribute -> (module, name)
_LAZY_IMPORTS = {
    # loader
    "load_amt": (".loader", "load_amt"),
    "clear_cache": (".loader", "clear_cache"),
    "get_value": (".loader", "get_value"),
    "get_aum": (".loader", "get_aum"),
    "get_leverage": (".loader", "get_leverage"),
    "get_asset": (".loader", "get_asset"),
    "find_assets": (".loader", "find_assets"),
    "cached_assets": (".loader", "cached_assets"),
    "get_table": (".loader", "get_table"),
    "_iter_assets": (".loader", "_iter_assets"),
    "assets": (".loader", "assets"),
    "asset_class": (".loader", "asset_class"),
    "_compile_rules": (".loader", "_compile_rules"),
    "_match_rules": (".loader", "_match_rules"),
    "asset_table": (".loader", "asset_table"),
    "asset_group": (".loader", "asset_group"),
    # table utilities (from table.py)
    "table_to_columns": (".table", "table_to_columns"),
    "table_to_rows": (".table", "table_to_rows"),
    "table_to_arrow": (".table", "table_to_arrow"),
    "table_to_jsonable": (".table", "table_to_jsonable"),
    "table_orientation": (".table", "table_orientation"),
    "table_nrows": (".table", "table_nrows"),
    "table_validate": (".table", "table_validate"),
    "table_column": (".table", "table_column"),
    "table_select_columns": (".table", "table_select_columns"),
    "table_add_column": (".table", "table_add_column"),
    "table_drop_columns": (".table", "table_drop_columns"),
    "table_replace_value": (".table", "table_replace_value"),
    "table_bind_rows": (".table", "table_bind_rows"),
    "table_unique_rows": (".table", "table_unique_rows"),
    "table_head": (".table", "table_head"),
    "table_sample": (".table", "table_sample"),
    "table_stack_cols": (".table", "table_stack_cols"),
    "table_left_join": (".table", "table_left_join"),
    "table_inner_join": (".table", "table_inner_join"),
    "table_unchop": (".table", "table_unchop"),
    "table_chop": (".table", "table_chop"),
    "format_table": (".table", "format_table"),
    "print_table": (".table", "print_table"),
    # arrow compute functions
    # arithmetic
    "table_add_arrow": (".table", "table_add_arrow"),
    "table_subtract_arrow": (".table", "table_subtract_arrow"),
    "table_multiply_arrow": (".table", "table_multiply_arrow"),
    "table_divide_arrow": (".table", "table_divide_arrow"),
    "table_negate_arrow": (".table", "table_negate_arrow"),
    "table_abs_arrow": (".table", "table_abs_arrow"),
    "table_sign_arrow": (".table", "table_sign_arrow"),
    "table_power_arrow": (".table", "table_power_arrow"),
    "table_sqrt_arrow": (".table", "table_sqrt_arrow"),
    "table_exp_arrow": (".table", "table_exp_arrow"),
    "table_ln_arrow": (".table", "table_ln_arrow"),
    "table_log10_arrow": (".table", "table_log10_arrow"),
    "table_log2_arrow": (".table", "table_log2_arrow"),
    "table_round_arrow": (".table", "table_round_arrow"),
    "table_ceil_arrow": (".table", "table_ceil_arrow"),
    "table_floor_arrow": (".table", "table_floor_arrow"),
    "table_trunc_arrow": (".table", "table_trunc_arrow"),
    # trigonometric
    "table_sin_arrow": (".table", "table_sin_arrow"),
    "table_cos_arrow": (".table", "table_cos_arrow"),
    "table_tan_arrow": (".table", "table_tan_arrow"),
    "table_asin_arrow": (".table", "table_asin_arrow"),
    "table_acos_arrow": (".table", "table_acos_arrow"),
    "table_atan_arrow": (".table", "table_atan_arrow"),
    "table_atan2_arrow": (".table", "table_atan2_arrow"),
    # comparison
    "table_equal_arrow": (".table", "table_equal_arrow"),
    "table_not_equal_arrow": (".table", "table_not_equal_arrow"),
    "table_less_arrow": (".table", "table_less_arrow"),
    "table_less_equal_arrow": (".table", "table_less_equal_arrow"),
    "table_greater_arrow": (".table", "table_greater_arrow"),
    "table_greater_equal_arrow": (".table", "table_greater_equal_arrow"),
    # null/value checks
    "table_is_null_arrow": (".table", "table_is_null_arrow"),
    "table_is_valid_arrow": (".table", "table_is_valid_arrow"),
    "table_is_nan_arrow": (".table", "table_is_nan_arrow"),
    "table_is_finite_arrow": (".table", "table_is_finite_arrow"),
    "table_is_in_arrow": (".table", "table_is_in_arrow"),
    # logical
    "table_and_arrow": (".table", "table_and_arrow"),
    "table_or_arrow": (".table", "table_or_arrow"),
    "table_xor_arrow": (".table", "table_xor_arrow"),
    "table_invert_arrow": (".table", "table_invert_arrow"),
    # string
    "table_upper_arrow": (".table", "table_upper_arrow"),
    "table_lower_arrow": (".table", "table_lower_arrow"),
    "table_capitalize_arrow": (".table", "table_capitalize_arrow"),
    "table_title_arrow": (".table", "table_title_arrow"),
    "table_strip_arrow": (".table", "table_strip_arrow"),
    "table_lstrip_arrow": (".table", "table_lstrip_arrow"),
    "table_rstrip_arrow": (".table", "table_rstrip_arrow"),
    "table_length_arrow": (".table", "table_length_arrow"),
    "table_starts_with_arrow": (".table", "table_starts_with_arrow"),
    "table_ends_with_arrow": (".table", "table_ends_with_arrow"),
    "table_contains_arrow": (".table", "table_contains_arrow"),
    "table_replace_substr_arrow": (".table", "table_replace_substr_arrow"),
    "table_split_arrow": (".table", "table_split_arrow"),
    # aggregates
    "table_summarize_arrow": (".table", "table_summarize_arrow"),
    "table_sum_arrow": (".table", "table_sum_arrow"),
    "table_mean_arrow": (".table", "table_mean_arrow"),
    "table_min_arrow": (".table", "table_min_arrow"),
    "table_max_arrow": (".table", "table_max_arrow"),
    "table_count_arrow": (".table", "table_count_arrow"),
    "table_count_distinct_arrow": (".table", "table_count_distinct_arrow"),
    "table_stddev_arrow": (".table", "table_stddev_arrow"),
    "table_variance_arrow": (".table", "table_variance_arrow"),
    "table_first_arrow": (".table", "table_first_arrow"),
    "table_last_arrow": (".table", "table_last_arrow"),
    "table_any_arrow": (".table", "table_any_arrow"),
    "table_all_arrow": (".table", "table_all_arrow"),
    # cumulative
    "table_cumsum_arrow": (".table", "table_cumsum_arrow"),
    "table_cumprod_arrow": (".table", "table_cumprod_arrow"),
    "table_cummin_arrow": (".table", "table_cummin_arrow"),
    "table_cummax_arrow": (".table", "table_cummax_arrow"),
    "table_cummean_arrow": (".table", "table_cummean_arrow"),
    "table_diff_arrow": (".table", "table_diff_arrow"),
    # selection
    "table_if_else_arrow": (".table", "table_if_else_arrow"),
    "table_coalesce_arrow": (".table", "table_coalesce_arrow"),
    "table_fill_null_arrow": (".table", "table_fill_null_arrow"),
    "table_fill_null_forward_arrow": (".table", "table_fill_null_forward_arrow"),
    "table_fill_null_backward_arrow": (".table", "table_fill_null_backward_arrow"),
    # filter
    "table_filter_arrow": (".table", "table_filter_arrow"),
    # backward compatibility alias
    "bind_rows": (".table", "table_bind_rows"),
    # tickers
    "_split_ticker": (".tickers", "_split_ticker"),
    "get_tschemas": (".tickers", "get_tschemas"),
    "find_tschemas": (".tickers", "find_tschemas"),
    "fut_spec2ticker": (".tickers", "fut_spec2ticker"),
    "fut_norm2act": (".tickers", "fut_norm2act"),
    "fut_act2norm": (".tickers", "fut_act2norm"),
    "clear_normalized_cache": (".tickers", "clear_normalized_cache"),
    "_tschma_dict_expand_bbgfc": (".tickers", "_tschma_dict_expand_bbgfc"),
    "_tschma_dict_expand_split": (".tickers", "_tschma_dict_expand_split"),
    "asset_straddle_tickers": (".tickers", "asset_straddle_tickers"),
    "get_straddle_days": (".tickers", "get_straddle_days"),
    "find_tickers": (".tickers", "find_tickers"),
    "find_tickers_ym": (".tickers", "find_tickers_ym"),
    # schedules
    "get_schedule": (".schedules", "get_schedule"),
    "find_schedules": (".schedules", "find_schedules"),
    "_split_code_value": (".schedules", "_split_code_value"),
    "find_straddle_yrs": (".schedules", "find_straddle_yrs"),
    "find_straddle_ym": (".schedules", "find_straddle_ym"),
    "get_straddle_yrs": (".schedules", "get_straddle_yrs"),
    "get_expand_ym": (".schedules", "get_expand_ym"),
    "get_days_ym": (".schedules", "get_days_ym"),
    "clear_days_cache": (".schedules", "clear_days_cache"),
    "count_straddle_days": (".schedules", "count_straddle_days"),
    "straddle_days": (".schedules", "straddle_days"),
    "count_straddles_days": (".schedules", "count_straddles_days"),
    "find_straddle_days": (".schedules", "find_straddle_days"),
    # straddle parsing
    "ntr": (".schedules", "ntr"),
    "ntry": (".schedules", "ntry"),
    "ntrm": (".schedules", "ntrm"),
    "xpr": (".schedules", "xpr"),
    "xpry": (".schedules", "xpry"),
    "xprm": (".schedules", "xprm"),
    "ntrc": (".schedules", "ntrc"),
    "ntrv": (".schedules", "ntrv"),
    "xprc": (".schedules", "xprc"),
    "xprv": (".schedules", "xprv"),
    "wgt": (".schedules", "wgt"),
}


def __getattr__(name: str):
    if name in _LAZY_IMPORTS:
        module_name, attr_name = _LAZY_IMPORTS[name]
        from importlib import import_module
        module = import_module(module_name, __package__)
        return getattr(module, attr_name)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
